apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'flink'
        static_configs:
          - targets: ['$OPERATOR_POD_IP:9249', '$JOB_MANAGER_POD_IP:9249', '$TASK_MANAGER_POD_IP:9249']
