apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: https://thanos-querier.openshift-monitoring.svc:9091
        jsonData:
          tlsSkipVerify: true
          httpHeaderName1: Authorization
        secureJsonData:
          httpHeaderValue1: 'Bearer $PROMETHEUS_TOKEN'
        editable: true
